/**
 * CSS Generator
 *
 * Converts a ThemeConfig into a CSS string with:
 * 1. CSS custom properties on :root and .dark
 * 2. Component styles using [data-slot] selectors
 */

import type { ThemeConfig, ThemeStyleProps } from '../theme-editor.types';
import { COMMON_STYLE_KEYS } from '../theme-editor.types';

export interface CSSGeneratorOptions {
	/** Wrap all selectors under this scope (for live preview isolation) */
	scopeSelector?: string;
	/** Include component styles or just CSS variables */
	includeComponentStyles?: boolean;
}

/**
 * Dangerous patterns that can escape CSS property context or inject malicious content.
 * Order matters — backslash removal runs first to prevent bypass via CSS escape sequences.
 */
const CSS_DANGEROUS_PATTERNS: RegExp[] = [
	/\\/g, // Backslash escapes (e.g., u\72l → url)
	/[{}]/g, // Curly braces — escapes property/rule context
	/;/g, // Semicolons — injects extra properties
	/url\s*\(/gi, // url() — data exfiltration via external requests
	/@import/gi, // @import — loads external stylesheets
	/expression\s*\(/gi, // expression() — IE XSS vector
	/javascript\s*:/gi, // javascript: pseudo-protocol
	/var\s*\(/gi, // var() — prevents variable injection chains
	/<!--/g, // HTML comment open
	/-->/g, // HTML comment close
	/<\/?[a-z]/gi, // HTML tags (e.g., </style><script>)
];

/**
 * Sanitize a CSS custom property value to prevent injection attacks.
 *
 * Strips dangerous patterns while preserving valid CSS values like:
 * - OKLCH/RGB/HSL colors: `oklch(0.5 0.2 250)`, `rgb(255, 0, 0)`, `#ff0000`
 * - Dimensions: `0.625rem`, `10px`, `0`
 * - Font stacks: `'Inter', system-ui, sans-serif`
 */
export function sanitizeCSSValue(value: string): string {
	let sanitized = value;
	let previous: string;
	do {
		previous = sanitized;
		for (const pattern of CSS_DANGEROUS_PATTERNS) {
			sanitized = sanitized.replace(pattern, '');
		}
	} while (sanitized !== previous);
	return sanitized.trim();
}

/** Generate a complete CSS theme string from a ThemeConfig */
export function generateThemeCSS(config: ThemeConfig, options?: CSSGeneratorOptions): string {
	const scope = options?.scopeSelector;
	const includeComponents = options?.includeComponentStyles ?? true;

	const parts: string[] = [
		'/* Momentum Headless Theme */',
		'/* Generated by @momentumcms/headless — Theme Editor */',
		'',
	];

	// CSS Custom Properties
	parts.push(generateVariablesBlock(config.light, scope ? `${scope}` : ':root'));
	parts.push('');
	parts.push(generateDarkVariablesBlock(config.light, config.dark, scope));

	if (includeComponents) {
		parts.push('');
		parts.push(generateComponentStyles(scope));
	}

	return parts.join('\n');
}

/** Sanitize a CSS custom property key (should be safe via TypeScript, belt-and-suspenders) */
function sanitizeKey(key: string): string {
	return key.replace(/[^a-zA-Z0-9-]/g, '');
}

/** Generate a :root { ... } block with all CSS custom properties */
function generateVariablesBlock(styles: ThemeStyleProps, selector: string): string {
	const lines = Object.entries(styles).map(
		([key, value]) => `  --${sanitizeKey(key)}: ${sanitizeCSSValue(value)};`,
	);
	return `${selector} {\n${lines.join('\n')}\n}`;
}

/** Generate .dark { ... } block with only values that differ from light mode */
function generateDarkVariablesBlock(
	light: ThemeStyleProps,
	dark: ThemeStyleProps,
	scope?: string,
): string {
	const selector = scope ? `${scope}.dark, ${scope} .dark` : '.dark';
	const entries: string[] = [];

	const allKeys: (keyof ThemeStyleProps)[] = Object.keys(dark) as Array<keyof ThemeStyleProps>; // eslint-disable-line @typescript-eslint/consistent-type-assertions -- ThemeStyleProps keys are string-typed
	for (const key of allKeys) {
		const value = dark[key];
		// Skip common keys (same in both modes) and identical values
		if (COMMON_STYLE_KEYS.includes(key) || light[key] === value) {
			continue;
		}
		entries.push(`  --${sanitizeKey(key)}: ${sanitizeCSSValue(value)};`);
	}

	if (entries.length === 0) return '';
	return `${selector} {\n${entries.join('\n')}\n}`;
}

/** Wrap a selector with optional scope */
function s(selector: string, scope?: string): string {
	return scope ? `${scope} ${selector}` : selector;
}

function shadowValue(): string {
	return [
		'var(--shadow-offset-x)',
		'var(--shadow-offset-y)',
		'var(--shadow-blur)',
		'var(--shadow-spread)',
		'color-mix(in srgb, var(--shadow-color) calc(var(--shadow-opacity) * 100%), transparent)',
	].join(' ');
}

/** Generate component styles using [data-slot] selectors */
function generateComponentStyles(scope?: string): string {
	const lines: string[] = ['/* === Component Styles === */'];

	// Helper to add a rule
	const rule = (selector: string, ...props: string[]): void => {
		lines.push(`${s(selector, scope)} {`);
		for (const prop of props) {
			lines.push(`  ${prop}`);
		}
		lines.push('}');
	};

	// Base reset — prevent app/Tailwind styles from leaking into preview
	lines.push('');
	lines.push('/* Base reset for all slotted elements */');
	rule(
		'[data-slot]',
		'box-sizing: border-box;',
		'margin: 0;',
		'padding: 0;',
		'border: 0;',
		'border-radius: 0;',
		'font: inherit;',
		'color: inherit;',
		'background: transparent;',
		'text-transform: none;',
		'letter-spacing: normal;',
		'text-decoration: none;',
		'vertical-align: baseline;',
		'min-width: 0;',
		'min-height: 0;',
	);

	// Button
	lines.push('');
	lines.push('/* Button */');
	rule(
		'[data-slot="button"]',
		'display: inline-flex;',
		'align-items: center;',
		'justify-content: center;',
		'gap: 0.5rem;',
		'font-family: var(--font-sans);',
		'font-weight: 500;',
		'font-size: 0.875rem;',
		'line-height: 1.25rem;',
		'border-radius: var(--radius);',
		'padding: 0.5rem 1rem;',
		'cursor: pointer;',
		'border: 1px solid transparent;',
		'background: var(--primary);',
		'color: var(--primary-foreground);',
		'transition: opacity 150ms;',
	);
	rule('[data-slot="button"]:hover', 'opacity: 0.9;');
	rule(
		'[data-slot="button"]:focus-visible',
		'outline: 2px solid var(--ring);',
		'outline-offset: 2px;',
	);
	rule('[data-slot="button"]:disabled', 'opacity: 0.5;', 'pointer-events: none;');

	// Button variants
	rule(
		'[data-slot="button"][data-variant="secondary"]',
		'background: var(--secondary);',
		'color: var(--secondary-foreground);',
	);
	rule(
		'[data-slot="button"][data-variant="outline"]',
		'background: transparent;',
		'color: var(--foreground);',
		'border-color: var(--input);',
	);
	rule(
		'[data-slot="button"][data-variant="outline"]:hover',
		'background: var(--accent);',
		'color: var(--accent-foreground);',
	);
	rule(
		'[data-slot="button"][data-variant="destructive"]',
		'background: var(--destructive);',
		'color: var(--destructive-foreground);',
	);
	rule(
		'[data-slot="button"][data-variant="ghost"]',
		'background: transparent;',
		'color: var(--foreground);',
		'border-color: transparent;',
	);
	rule(
		'[data-slot="button"][data-variant="ghost"]:hover',
		'background: var(--accent);',
		'color: var(--accent-foreground);',
	);
	rule(
		'[data-slot="button"][data-variant="link"]',
		'background: transparent;',
		'color: var(--primary);',
		'border-color: transparent;',
		'padding: 0;',
		'text-decoration: underline;',
		'text-underline-offset: 4px;',
	);

	// Input
	lines.push('');
	lines.push('/* Input */');
	rule(
		'[data-slot="input"]',
		'display: flex;',
		'width: 100%;',
		'border: 1px solid var(--input);',
		'border-radius: var(--radius);',
		'background: transparent;',
		'color: var(--foreground);',
		'font-family: var(--font-sans);',
		'font-size: 0.875rem;',
		'line-height: 1.25rem;',
		'padding: 0.5rem 0.75rem;',
	);
	rule(
		'[data-slot="input"]:focus-visible',
		'outline: 2px solid var(--ring);',
		'outline-offset: 2px;',
	);
	rule('[data-slot="input"]::placeholder', 'color: var(--muted-foreground);');

	// Textarea
	lines.push('');
	lines.push('/* Textarea */');
	rule(
		'[data-slot="textarea"]',
		'display: flex;',
		'width: 100%;',
		'min-height: 5rem;',
		'border: 1px solid var(--input);',
		'border-radius: var(--radius);',
		'background: transparent;',
		'color: var(--foreground);',
		'font-family: var(--font-sans);',
		'font-size: 0.875rem;',
		'padding: 0.5rem 0.75rem;',
		'resize: vertical;',
	);
	rule(
		'[data-slot="textarea"]:focus-visible',
		'outline: 2px solid var(--ring);',
		'outline-offset: 2px;',
	);

	// Checkbox
	lines.push('');
	lines.push('/* Checkbox */');
	rule(
		'[data-slot="checkbox"]',
		'display: inline-flex;',
		'align-items: center;',
		'justify-content: center;',
		'width: 1rem;',
		'height: 1rem;',
		'min-width: 1rem;',
		'min-height: 1rem;',
		'max-width: 1rem;',
		'max-height: 1rem;',
		'border: 1px solid var(--border);',
		'border-radius: calc(var(--radius) * 0.5);',
		'cursor: pointer;',
		'transition: background-color 150ms, border-color 150ms;',
		'position: relative;',
		'flex-shrink: 0;',
	);
	rule(
		'[data-slot="checkbox"]::after',
		'content: "";',
		'display: none;',
		'width: 0.25rem;',
		'height: 0.5rem;',
		'border: solid var(--primary-foreground);',
		'border-width: 0 2px 2px 0;',
		'transform: rotate(45deg);',
	);
	rule(
		'[data-slot="checkbox"][data-state="checked"]',
		'background: var(--primary);',
		'color: var(--primary-foreground);',
		'border-color: var(--primary);',
	);
	rule('[data-slot="checkbox"][data-state="checked"]::after', 'display: block;');
	rule(
		'[data-slot="checkbox"]:focus-visible',
		'outline: 2px solid var(--ring);',
		'outline-offset: 2px;',
	);

	// Switch
	lines.push('');
	lines.push('/* Switch */');
	rule(
		'[data-slot="switch"]',
		'display: inline-flex;',
		'align-items: center;',
		'width: 2.75rem;',
		'height: 1.5rem;',
		'min-width: 2.75rem;',
		'min-height: 1.5rem;',
		'max-width: 2.75rem;',
		'max-height: 1.5rem;',
		'border-radius: 9999px;',
		'background: var(--input);',
		'cursor: pointer;',
		'padding: 0.125rem;',
		'transition: background-color 150ms;',
		'position: relative;',
		'flex-shrink: 0;',
	);
	rule(
		'[data-slot="switch"]::after',
		'content: "";',
		'display: block;',
		'width: 1.25rem;',
		'height: 1.25rem;',
		'border-radius: 9999px;',
		'background: var(--background);',
		'transition: transform 150ms;',
		'transform: translateX(0);',
	);
	rule('[data-slot="switch"][data-state="checked"]', 'background: var(--primary);');
	rule('[data-slot="switch"][data-state="checked"]::after', 'transform: translateX(1.25rem);');
	rule(
		'[data-slot="switch"]:focus-visible',
		'outline: 2px solid var(--ring);',
		'outline-offset: 2px;',
	);

	// Radio
	lines.push('');
	lines.push('/* Radio */');
	rule('[data-slot="radio-group"]', 'display: flex;', 'flex-direction: column;', 'gap: 0.5rem;');
	rule(
		'[data-slot="radio-item"]',
		'display: inline-flex;',
		'align-items: center;',
		'justify-content: center;',
		'width: 1rem;',
		'height: 1rem;',
		'min-width: 1rem;',
		'min-height: 1rem;',
		'max-width: 1rem;',
		'max-height: 1rem;',
		'border: 1px solid var(--border);',
		'border-radius: 9999px;',
		'cursor: pointer;',
		'position: relative;',
		'flex-shrink: 0;',
	);
	rule(
		'[data-slot="radio-item"]::after',
		'content: "";',
		'display: none;',
		'width: 0.5rem;',
		'height: 0.5rem;',
		'border-radius: 9999px;',
		'background: var(--primary);',
	);
	rule('[data-slot="radio-item"][data-state="checked"]', 'border-color: var(--primary);');
	rule('[data-slot="radio-item"][data-state="checked"]::after', 'display: block;');
	rule(
		'[data-slot="radio-item"]:focus-visible',
		'outline: 2px solid var(--ring);',
		'outline-offset: 2px;',
	);

	// Tabs
	lines.push('');
	lines.push('/* Tabs */');
	rule('[data-slot="tabs"]', 'width: 100%;');
	rule(
		'[data-slot="tab-list"]',
		'display: flex;',
		'border-bottom: 1px solid var(--border);',
		'gap: 0;',
	);
	rule(
		'[data-slot="tab"]',
		'display: inline-flex;',
		'align-items: center;',
		'justify-content: center;',
		'padding: 0.5rem 1rem;',
		'font-family: var(--font-sans);',
		'font-size: 0.875rem;',
		'font-weight: 500;',
		'color: var(--muted-foreground);',
		'cursor: pointer;',
		'border-bottom: 2px solid transparent;',
		'transition: color 150ms, border-color 150ms;',
	);
	rule(
		'[data-slot="tab"][data-state="selected"]',
		'color: var(--foreground);',
		'border-bottom-color: var(--primary);',
	);
	rule(
		'[data-slot="tab"]:focus-visible',
		'outline: 2px solid var(--ring);',
		'outline-offset: -2px;',
	);
	rule(
		'[data-slot="tab-panel"]',
		'padding: 1rem 0;',
		'font-family: var(--font-sans);',
		'color: var(--foreground);',
	);

	// Accordion
	lines.push('');
	lines.push('/* Accordion */');
	rule('[data-slot="accordion"]', 'width: 100%;');
	rule('[data-slot="accordion-item"]', 'border-bottom: 1px solid var(--border);');
	rule(
		'[data-slot="accordion-trigger"]',
		'display: flex;',
		'width: 100%;',
		'align-items: center;',
		'justify-content: space-between;',
		'padding: 1rem 0;',
		'font-family: var(--font-sans);',
		'font-weight: 500;',
		'color: var(--foreground);',
		'cursor: pointer;',
		'transition: color 150ms;',
	);
	rule('[data-slot="accordion-trigger"]:hover', 'color: var(--primary);');
	rule(
		'[data-slot="accordion-trigger"]:focus-visible',
		'outline: 2px solid var(--ring);',
		'outline-offset: 2px;',
	);
	rule(
		'[data-slot="accordion-content"]',
		'overflow: hidden;',
		'font-family: var(--font-sans);',
		'color: var(--muted-foreground);',
		'font-size: 0.875rem;',
		'padding: 0.75rem 0;',
	);

	// Select
	lines.push('');
	lines.push('/* Select */');
	rule('[data-slot="select"]', 'position: relative;');
	rule(
		'[data-slot="select-trigger"]',
		'display: inline-flex;',
		'align-items: center;',
		'justify-content: space-between;',
		'gap: 0.5rem;',
		'border: 1px solid var(--input);',
		'border-radius: var(--radius);',
		'background: transparent;',
		'color: var(--foreground);',
		'font-family: var(--font-sans);',
		'font-size: 0.875rem;',
		'padding: 0.5rem 0.75rem;',
		'cursor: pointer;',
	);
	rule(
		'[data-slot="select-trigger"]:focus-visible',
		'outline: 2px solid var(--ring);',
		'outline-offset: 2px;',
	);
	rule('[data-slot="select-value"]', 'font-family: var(--font-sans);', 'color: var(--foreground);');
	rule(
		'[data-slot="select-content"]',
		'background: var(--popover);',
		'color: var(--popover-foreground);',
		'border: 1px solid var(--border);',
		'border-radius: var(--radius);',
		`box-shadow: ${shadowValue()};`,
		'padding: 0.25rem;',
	);
	rule(
		'[data-slot="select-item"]',
		'display: flex;',
		'align-items: center;',
		'padding: 0.375rem 0.5rem;',
		'border-radius: calc(var(--radius) * 0.5);',
		'font-size: 0.875rem;',
		'cursor: pointer;',
		'transition: background-color 150ms;',
	);
	rule(
		'[data-slot="select-item"]:hover',
		'background: var(--accent);',
		'color: var(--accent-foreground);',
	);
	rule(
		'[data-slot="select-item"][data-state="selected"]',
		'background: var(--accent);',
		'color: var(--accent-foreground);',
	);

	// Collapsible
	lines.push('');
	lines.push('/* Collapsible */');
	rule('[data-slot="collapsible"]', 'width: 100%;');
	rule(
		'[data-slot="collapsible-trigger"]',
		'cursor: pointer;',
		'font-family: var(--font-sans);',
		'color: var(--foreground);',
	);
	rule('[data-slot="collapsible-content"]', 'overflow: hidden;', 'color: var(--muted-foreground);');

	// Toggle
	lines.push('');
	lines.push('/* Toggle */');
	rule(
		'[data-slot="toggle"]',
		'display: inline-flex;',
		'align-items: center;',
		'justify-content: center;',
		'border-radius: var(--radius);',
		'padding: 0.5rem;',
		'font-family: var(--font-sans);',
		'font-size: 0.875rem;',
		'font-weight: 500;',
		'color: var(--muted-foreground);',
		'cursor: pointer;',
		'background: transparent;',
		'border: 1px solid transparent;',
		'transition: background-color 150ms, color 150ms;',
	);
	rule(
		'[data-slot="toggle"]:hover',
		'background: var(--accent);',
		'color: var(--accent-foreground);',
	);
	rule(
		'[data-slot="toggle"][data-state="on"]',
		'background: var(--accent);',
		'color: var(--accent-foreground);',
	);
	rule(
		'[data-slot="toggle"]:focus-visible',
		'outline: 2px solid var(--ring);',
		'outline-offset: 2px;',
	);
	rule('[data-slot="toggle-group"]', 'display: inline-flex;', 'gap: 0.25rem;');
	rule(
		'[data-slot="toggle-item"]',
		'display: inline-flex;',
		'align-items: center;',
		'justify-content: center;',
		'border-radius: var(--radius);',
		'padding: 0.5rem;',
		'font-family: var(--font-sans);',
		'font-size: 0.875rem;',
		'font-weight: 500;',
		'color: var(--muted-foreground);',
		'cursor: pointer;',
		'background: transparent;',
		'border: 1px solid var(--border);',
		'transition: background-color 150ms, color 150ms;',
	);
	rule(
		'[data-slot="toggle-item"]:hover',
		'background: var(--accent);',
		'color: var(--accent-foreground);',
	);
	rule(
		'[data-slot="toggle-item"][data-state="on"]',
		'background: var(--accent);',
		'color: var(--accent-foreground);',
	);
	rule(
		'[data-slot="toggle-item"]:focus-visible',
		'outline: 2px solid var(--ring);',
		'outline-offset: 2px;',
	);

	// Dialog
	lines.push('');
	lines.push('/* Dialog */');
	rule(
		'[data-slot="dialog"]',
		'background: var(--card);',
		'color: var(--card-foreground);',
		'border: 1px solid var(--border);',
		'border-radius: var(--radius);',
		`box-shadow: ${shadowValue()};`,
		'padding: 1.5rem;',
	);
	rule(
		'[data-slot="dialog-title"]',
		'font-family: var(--font-sans);',
		'font-size: 1.125rem;',
		'font-weight: 600;',
		'color: var(--foreground);',
	);
	rule(
		'[data-slot="dialog-description"]',
		'font-family: var(--font-sans);',
		'font-size: 0.875rem;',
		'color: var(--muted-foreground);',
	);
	rule(
		'[data-slot="dialog-close"]',
		'cursor: pointer;',
		'color: var(--muted-foreground);',
		'transition: color 150ms;',
	);
	rule('[data-slot="dialog-close"]:hover', 'color: var(--foreground);');

	// Alert Dialog
	lines.push('');
	lines.push('/* Alert Dialog */');
	rule(
		'[data-slot="alert-dialog"]',
		'background: var(--card);',
		'color: var(--card-foreground);',
		'border: 1px solid var(--border);',
		'border-radius: var(--radius);',
		`box-shadow: ${shadowValue()};`,
		'padding: 1.5rem;',
	);
	rule(
		'[data-slot="alert-dialog-title"]',
		'font-family: var(--font-sans);',
		'font-size: 1.125rem;',
		'font-weight: 600;',
		'color: var(--foreground);',
	);
	rule(
		'[data-slot="alert-dialog-description"]',
		'font-family: var(--font-sans);',
		'font-size: 0.875rem;',
		'color: var(--muted-foreground);',
	);
	rule(
		'[data-slot="alert-dialog-action"]',
		'display: inline-flex;',
		'align-items: center;',
		'justify-content: center;',
		'border-radius: var(--radius);',
		'padding: 0.5rem 1rem;',
		'font-family: var(--font-sans);',
		'font-size: 0.875rem;',
		'font-weight: 500;',
		'background: var(--primary);',
		'color: var(--primary-foreground);',
		'cursor: pointer;',
		'border: 1px solid transparent;',
	);
	rule(
		'[data-slot="alert-dialog-cancel"]',
		'display: inline-flex;',
		'align-items: center;',
		'justify-content: center;',
		'border-radius: var(--radius);',
		'padding: 0.5rem 1rem;',
		'font-family: var(--font-sans);',
		'font-size: 0.875rem;',
		'font-weight: 500;',
		'background: var(--secondary);',
		'color: var(--secondary-foreground);',
		'cursor: pointer;',
		'border: 1px solid var(--border);',
	);

	// Drawer
	lines.push('');
	lines.push('/* Drawer */');
	rule(
		'[data-slot="drawer"]',
		'background: var(--card);',
		'color: var(--card-foreground);',
		'border: 1px solid var(--border);',
		`box-shadow: ${shadowValue()};`,
		'padding: 1.5rem;',
	);
	rule(
		'[data-slot="drawer-title"]',
		'font-family: var(--font-sans);',
		'font-size: 1.125rem;',
		'font-weight: 600;',
		'color: var(--foreground);',
	);
	rule(
		'[data-slot="drawer-description"]',
		'font-family: var(--font-sans);',
		'font-size: 0.875rem;',
		'color: var(--muted-foreground);',
	);
	rule(
		'[data-slot="drawer-close"]',
		'cursor: pointer;',
		'color: var(--muted-foreground);',
		'transition: color 150ms;',
	);
	rule('[data-slot="drawer-close"]:hover', 'color: var(--foreground);');

	// Toast
	lines.push('');
	lines.push('/* Toast */');
	rule(
		'[data-slot="toast-container"]',
		'position: fixed;',
		'z-index: 50;',
		'pointer-events: none;',
	);
	rule(
		'[data-slot="toast"]',
		'background: var(--card);',
		'color: var(--card-foreground);',
		'border: 1px solid var(--border);',
		'border-radius: var(--radius);',
		`box-shadow: ${shadowValue()};`,
		'padding: 1rem 1.5rem;',
		'pointer-events: auto;',
	);
	rule(
		'[data-slot="toast"][data-variant="destructive"]',
		'border-color: var(--destructive);',
		'color: var(--destructive);',
	);
	rule(
		'[data-slot="toast"][data-variant="success"]',
		'border-color: var(--primary);',
		'color: var(--primary);',
	);
	rule(
		'[data-slot="toast-title"]',
		'font-family: var(--font-sans);',
		'font-weight: 600;',
		'font-size: 0.875rem;',
		'color: inherit;',
	);
	rule(
		'[data-slot="toast-description"]',
		'font-family: var(--font-sans);',
		'font-size: 0.75rem;',
		'color: var(--muted-foreground);',
	);
	rule(
		'[data-slot="toast-action"]',
		'display: inline-flex;',
		'align-items: center;',
		'border-radius: var(--radius);',
		'padding: 0.25rem 0.5rem;',
		'font-size: 0.75rem;',
		'font-weight: 500;',
		'border: 1px solid var(--border);',
		'cursor: pointer;',
		'background: transparent;',
		'color: var(--foreground);',
		'transition: background-color 150ms;',
	);
	rule('[data-slot="toast-action"]:hover', 'background: var(--accent);');
	rule(
		'[data-slot="toast-dismiss"]',
		'cursor: pointer;',
		'color: var(--muted-foreground);',
		'transition: color 150ms;',
	);
	rule('[data-slot="toast-dismiss"]:hover', 'color: var(--foreground);');

	// Progress
	lines.push('');
	lines.push('/* Progress */');
	rule(
		'[data-slot="progress"]',
		'position: relative;',
		'width: 100%;',
		'height: 0.5rem;',
		'background: var(--muted);',
		'border-radius: var(--radius);',
		'overflow: hidden;',
	);
	// The fill indicator uses --progress-value CSS custom property (set via style binding)
	rule(
		'[data-slot="progress"]::after',
		'content: "";',
		'position: absolute;',
		'top: 0;',
		'left: 0;',
		'bottom: 0;',
		'width: calc(var(--progress-value, 0) * 1%);',
		'background: var(--primary);',
		'border-radius: var(--radius);',
		'transition: width 300ms;',
	);

	// Separator
	lines.push('');
	lines.push('/* Separator */');
	rule('[data-slot="separator"]', 'background: var(--border);', 'height: 1px;', 'width: 100%;');
	rule('[data-slot="separator"][data-orientation="vertical"]', 'width: 1px;', 'height: 100%;');

	// Spinner
	lines.push('');
	lines.push('/* Spinner */');
	rule(
		'[data-slot="spinner"]',
		'display: inline-block;',
		'width: 1rem;',
		'height: 1rem;',
		'min-width: 1rem;',
		'min-height: 1rem;',
		'max-width: 1rem;',
		'max-height: 1rem;',
		'color: var(--muted-foreground);',
		'position: relative;',
	);
	rule(
		'[data-slot="spinner"]::after',
		'content: "";',
		'display: block;',
		'width: 100%;',
		'height: 100%;',
		'border: 2px solid var(--muted);',
		'border-top-color: currentColor;',
		'border-radius: 9999px;',
		'animation: spinner-rotate 0.6s linear infinite;',
	);

	// Skeleton
	lines.push('');
	lines.push('/* Skeleton */');
	rule(
		'[data-slot="skeleton"]',
		'background: var(--muted);',
		'border-radius: var(--radius);',
		'animation: skeleton-pulse 2s ease-in-out infinite;',
	);

	// Chips
	lines.push('');
	lines.push('/* Chips */');
	rule(
		'[data-slot="chips"]',
		'display: flex;',
		'flex-wrap: wrap;',
		'gap: 0.25rem;',
		'align-items: center;',
		'border: 1px solid var(--input);',
		'border-radius: var(--radius);',
		'padding: 0.25rem;',
	);
	rule(
		'[data-slot="chip"]',
		'display: inline-flex;',
		'align-items: center;',
		'gap: 0.25rem;',
		'background: var(--secondary);',
		'color: var(--secondary-foreground);',
		'border-radius: var(--radius);',
		'padding: 0.25rem 0.5rem;',
		'font-family: var(--font-sans);',
		'font-size: 0.75rem;',
	);
	rule(
		'[data-slot="chip-input"]',
		'border: none;',
		'background: transparent;',
		'color: var(--foreground);',
		'font-family: var(--font-sans);',
		'font-size: 0.875rem;',
		'outline: none;',
	);
	rule(
		'[data-slot="chip-remove"]',
		'cursor: pointer;',
		'color: var(--muted-foreground);',
		'transition: color 150ms;',
	);
	rule('[data-slot="chip-remove"]:hover', 'color: var(--foreground);');

	// Field / Label
	lines.push('');
	lines.push('/* Field & Label */');
	rule('[data-slot="field"]', 'display: flex;', 'flex-direction: column;', 'gap: 0.375rem;');
	rule(
		'[data-slot="label"]',
		'font-family: var(--font-sans);',
		'font-size: 0.875rem;',
		'font-weight: 500;',
		'color: var(--foreground);',
		'text-transform: none;',
		'letter-spacing: normal;',
	);
	rule(
		'[data-slot="description"]',
		'font-family: var(--font-sans);',
		'font-size: 0.75rem;',
		'color: var(--muted-foreground);',
	);
	rule(
		'[data-slot="error"]',
		'font-family: var(--font-sans);',
		'font-size: 0.75rem;',
		'color: var(--destructive);',
	);

	// Menu
	lines.push('');
	lines.push('/* Menu */');
	rule(
		'[data-slot="menu"]',
		'background: var(--popover);',
		'color: var(--popover-foreground);',
		'border: 1px solid var(--border);',
		'border-radius: var(--radius);',
		`box-shadow: ${shadowValue()};`,
		'padding: 0.25rem;',
		'min-width: 8rem;',
	);
	rule(
		'[data-slot="menu-bar"]',
		'display: flex;',
		'align-items: center;',
		'gap: 0.25rem;',
		'background: var(--background);',
		'border: 1px solid var(--border);',
		'border-radius: var(--radius);',
		'padding: 0.25rem;',
	);
	rule(
		'[data-slot="menu-trigger"]',
		'display: inline-flex;',
		'align-items: center;',
		'font-family: var(--font-sans);',
		'font-size: 0.875rem;',
		'font-weight: 500;',
		'color: var(--foreground);',
		'cursor: pointer;',
		'padding: 0.375rem 0.5rem;',
		'border-radius: calc(var(--radius) * 0.5);',
		'transition: background-color 150ms;',
	);
	rule('[data-slot="menu-trigger"]:hover', 'background: var(--accent);');
	rule(
		'[data-slot="menu-item"]',
		'display: flex;',
		'align-items: center;',
		'gap: 0.5rem;',
		'padding: 0.375rem 0.5rem;',
		'border-radius: calc(var(--radius) * 0.5);',
		'font-family: var(--font-sans);',
		'font-size: 0.875rem;',
		'cursor: pointer;',
		'color: var(--foreground);',
		'transition: background-color 150ms;',
	);
	rule(
		'[data-slot="menu-item"]:hover',
		'background: var(--accent);',
		'color: var(--accent-foreground);',
	);
	rule(
		'[data-slot="menu-item"]:focus-visible',
		'outline: 2px solid var(--ring);',
		'outline-offset: -2px;',
	);
	rule('[data-slot="menu-item"][data-disabled]', 'opacity: 0.5;', 'pointer-events: none;');

	// Context Menu
	lines.push('');
	lines.push('/* Context Menu */');
	rule(
		'[data-slot="context-menu-content"]',
		'background: var(--popover);',
		'color: var(--popover-foreground);',
		'border: 1px solid var(--border);',
		'border-radius: var(--radius);',
		`box-shadow: ${shadowValue()};`,
		'padding: 0.25rem;',
		'min-width: 8rem;',
	);

	// Listbox
	lines.push('');
	lines.push('/* Listbox */');
	rule(
		'[data-slot="listbox"]',
		'background: var(--popover);',
		'color: var(--popover-foreground);',
		'border: 1px solid var(--border);',
		'border-radius: var(--radius);',
		'padding: 0.25rem;',
		'overflow-y: auto;',
	);
	rule(
		'[data-slot="option"]',
		'display: flex;',
		'align-items: center;',
		'gap: 0.5rem;',
		'padding: 0.375rem 0.5rem;',
		'border-radius: calc(var(--radius) * 0.5);',
		'font-family: var(--font-sans);',
		'font-size: 0.875rem;',
		'cursor: pointer;',
		'transition: background-color 150ms;',
	);
	rule(
		'[data-slot="option"]:hover',
		'background: var(--accent);',
		'color: var(--accent-foreground);',
	);
	rule(
		'[data-slot="option"][data-state="selected"]',
		'background: var(--accent);',
		'color: var(--accent-foreground);',
	);
	rule(
		'[data-slot="option"]:focus-visible',
		'outline: 2px solid var(--ring);',
		'outline-offset: -2px;',
	);

	// Combobox
	lines.push('');
	lines.push('/* Combobox */');
	rule('[data-slot="combobox"]', 'position: relative;', 'width: 100%;');
	rule(
		'[data-slot="combobox-input"]',
		'display: flex;',
		'width: 100%;',
		'border: 1px solid var(--input);',
		'border-radius: var(--radius);',
		'background: transparent;',
		'color: var(--foreground);',
		'font-family: var(--font-sans);',
		'font-size: 0.875rem;',
		'padding: 0.5rem 0.75rem;',
	);
	rule(
		'[data-slot="combobox-input"]:focus-visible',
		'outline: 2px solid var(--ring);',
		'outline-offset: 2px;',
	);
	rule(
		'[data-slot="combobox-popup"]',
		'background: var(--popover);',
		'color: var(--popover-foreground);',
		'border: 1px solid var(--border);',
		'border-radius: var(--radius);',
		`box-shadow: ${shadowValue()};`,
		'padding: 0.25rem;',
	);

	// Command
	lines.push('');
	lines.push('/* Command */');
	rule(
		'[data-slot="command"]',
		'background: var(--popover);',
		'color: var(--popover-foreground);',
		'border: 1px solid var(--border);',
		'border-radius: var(--radius);',
		'overflow: hidden;',
	);
	rule(
		'[data-slot="command-input"]',
		'display: flex;',
		'width: 100%;',
		'border: none;',
		'border-bottom: 1px solid var(--border);',
		'background: transparent;',
		'color: var(--foreground);',
		'font-family: var(--font-sans);',
		'font-size: 0.875rem;',
		'padding: 0.75rem;',
		'outline: none;',
	);
	rule('[data-slot="command-input"]::placeholder', 'color: var(--muted-foreground);');
	rule(
		'[data-slot="command-list"]',
		'max-height: 18rem;',
		'overflow-y: auto;',
		'padding: 0.25rem;',
	);
	rule('[data-slot="command-group"]', 'padding: 0.25rem 0;');
	rule(
		'[data-slot="command-item"]',
		'display: flex;',
		'align-items: center;',
		'gap: 0.5rem;',
		'padding: 0.375rem 0.5rem;',
		'border-radius: calc(var(--radius) * 0.5);',
		'font-family: var(--font-sans);',
		'font-size: 0.875rem;',
		'cursor: pointer;',
		'transition: background-color 150ms;',
	);
	rule(
		'[data-slot="command-item"]:hover',
		'background: var(--accent);',
		'color: var(--accent-foreground);',
	);
	rule(
		'[data-slot="command-item"][data-state="selected"]',
		'background: var(--accent);',
		'color: var(--accent-foreground);',
	);
	rule(
		'[data-slot="command-empty"]',
		'padding: 1.5rem;',
		'text-align: center;',
		'font-family: var(--font-sans);',
		'font-size: 0.875rem;',
		'color: var(--muted-foreground);',
	);
	rule(
		'[data-slot="command-separator"]',
		'background: var(--border);',
		'height: 1px;',
		'margin: 0.25rem 0;',
	);
	rule(
		'[data-slot="command-dialog"]',
		'background: var(--card);',
		'color: var(--card-foreground);',
		'border: 1px solid var(--border);',
		'border-radius: var(--radius);',
		`box-shadow: ${shadowValue()};`,
		'overflow: hidden;',
	);
	rule('[data-slot="command-dialog-panel"]', 'overflow: hidden;');

	// Popover
	lines.push('');
	lines.push('/* Popover */');
	rule(
		'[data-slot="popover-content"]',
		'background: var(--popover);',
		'color: var(--popover-foreground);',
		'border: 1px solid var(--border);',
		'border-radius: var(--radius);',
		`box-shadow: ${shadowValue()};`,
		'padding: 1rem;',
	);

	// Tooltip
	lines.push('');
	lines.push('/* Tooltip */');
	rule(
		'[data-slot="tooltip-content"]',
		'background: var(--primary);',
		'color: var(--primary-foreground);',
		'border-radius: calc(var(--radius) * 0.5);',
		'padding: 0.375rem 0.75rem;',
		'font-family: var(--font-sans);',
		'font-size: 0.75rem;',
		`box-shadow: ${shadowValue()};`,
	);

	// Hover Card
	lines.push('');
	lines.push('/* Hover Card */');
	rule(
		'[data-slot="hover-card-content"]',
		'background: var(--popover);',
		'color: var(--popover-foreground);',
		'border: 1px solid var(--border);',
		'border-radius: var(--radius);',
		`box-shadow: ${shadowValue()};`,
		'padding: 1rem;',
	);

	// Grid
	lines.push('');
	lines.push('/* Grid */');
	rule(
		'[data-slot="grid"]',
		'display: grid;',
		'width: 100%;',
		'border: 1px solid var(--border);',
		'border-radius: var(--radius);',
		'overflow: hidden;',
		'font-family: var(--font-sans);',
		'font-size: 0.875rem;',
	);
	rule(
		'[data-slot="grid-row"]',
		'display: grid;',
		'grid-template-columns: subgrid;',
		'grid-column: 1 / -1;',
		'border-bottom: 1px solid var(--border);',
	);
	rule('[data-slot="grid-row"]:last-child', 'border-bottom: none;');
	rule(
		'[data-slot="grid-cell"]',
		'padding: 0.5rem 0.75rem;',
		'color: var(--foreground);',
		'border-right: 1px solid var(--border);',
	);
	rule('[data-slot="grid-cell"]:last-child', 'border-right: none;');
	rule(
		'[data-slot="grid-cell"]:focus-visible',
		'outline: 2px solid var(--ring);',
		'outline-offset: -2px;',
	);

	// Tree
	lines.push('');
	lines.push('/* Tree */');
	rule(
		'[data-slot="tree"]',
		'font-family: var(--font-sans);',
		'font-size: 0.875rem;',
		'color: var(--foreground);',
	);
	rule(
		'[data-slot="tree-item"]',
		'display: flex;',
		'align-items: center;',
		'padding: 0.25rem 0.5rem;',
		'border-radius: calc(var(--radius) * 0.5);',
		'cursor: pointer;',
		'transition: background-color 150ms;',
	);
	rule('[data-slot="tree-item"]:hover', 'background: var(--accent);');
	rule(
		'[data-slot="tree-item"][data-state="selected"]',
		'background: var(--accent);',
		'color: var(--accent-foreground);',
	);
	rule(
		'[data-slot="tree-item"]:focus-visible',
		'outline: 2px solid var(--ring);',
		'outline-offset: -2px;',
	);
	rule('[data-slot="tree-item-group"]', 'padding-left: 1rem;');

	// Toolbar
	lines.push('');
	lines.push('/* Toolbar */');
	rule(
		'[data-slot="toolbar"]',
		'display: flex;',
		'align-items: center;',
		'gap: 0.25rem;',
		'background: var(--background);',
		'border: 1px solid var(--border);',
		'border-radius: var(--radius);',
		'padding: 0.25rem;',
	);
	rule(
		'[data-slot="toolbar-widget"]',
		'display: inline-flex;',
		'align-items: center;',
		'justify-content: center;',
		'padding: 0.375rem 0.5rem;',
		'border-radius: calc(var(--radius) * 0.5);',
		'font-family: var(--font-sans);',
		'font-size: 0.875rem;',
		'color: var(--foreground);',
		'cursor: pointer;',
		'transition: background-color 150ms;',
	);
	rule('[data-slot="toolbar-widget"]:hover', 'background: var(--accent);');
	rule(
		'[data-slot="toolbar-widget"]:focus-visible',
		'outline: 2px solid var(--ring);',
		'outline-offset: -2px;',
	);
	rule(
		'[data-slot="toolbar-widget-group"]',
		'display: inline-flex;',
		'align-items: center;',
		'gap: 0;',
		'border: 1px solid var(--border);',
		'border-radius: var(--radius);',
		'overflow: hidden;',
	);

	// Keyframes
	lines.push('');
	lines.push('/* Keyframes */');
	lines.push(`@keyframes skeleton-pulse {`);
	lines.push('  0%, 100% { opacity: 1; }');
	lines.push('  50% { opacity: 0.5; }');
	lines.push('}');
	lines.push(`@keyframes spinner-rotate {`);
	lines.push('  to { transform: rotate(360deg); }');
	lines.push('}');

	lines.push('');
	return lines.join('\n');
}
