/**
 * Generate a self-contained, framework-agnostic TypeScript API client.
 *
 * The output file imports types from the generated types file and inlines
 * all runtime code (fetch wrapper, error class, collection/global clients).
 * Only the factory's typed accessor map is project-specific.
 */

import { slugToPascalCase, safeQuote, needsQuoting } from './field-to-typescript';
import type { MomentumConfig } from './generator-types';
import { resolveAllCollections } from './generator-types';

export function generateClientCode(config: MomentumConfig, typesImportPath: string): string {
	const allCollections = resolveAllCollections(config);
	const globals = config.globals ?? [];
	const lines: string[] = [];

	// Header
	lines.push('/**');
	lines.push(' * AUTO-GENERATED by @momentumcms/core');
	lines.push(' * DO NOT EDIT - regenerate with: nx run <app>:generate');
	lines.push(' */');
	lines.push('');

	// Collect all type names needed for the import
	const typeImports: string[] = [];
	for (const col of allCollections) {
		const name = slugToPascalCase(col.slug);
		typeImports.push(name);
		typeImports.push(`${name}WhereClause`);
	}
	for (const global of globals) {
		typeImports.push(slugToPascalCase(global.slug) + 'Global');
	}

	lines.push(`import type {`);
	for (const t of typeImports) {
		lines.push(`\t${t},`);
	}
	lines.push(`} from ${JSON.stringify(typesImportPath)};`);
	lines.push('');

	// Error class
	lines.push(`// ── Error ──────────────────────────────────────`);
	lines.push('');
	lines.push(`export class MomentumClientError extends Error {`);
	lines.push(`\treadonly status: number;`);
	lines.push(`\treadonly fieldErrors: Array<{ field: string; message: string }>;`);
	lines.push('');
	lines.push(`\tconstructor(`);
	lines.push(`\t\tmessage: string,`);
	lines.push(`\t\tstatus = 500,`);
	lines.push(`\t\tfieldErrors: Array<{ field: string; message: string }> = [],`);
	lines.push(`\t) {`);
	lines.push(`\t\tsuper(message);`);
	lines.push(`\t\tthis.name = 'MomentumClientError';`);
	lines.push(`\t\tthis.status = status;`);
	lines.push(`\t\tthis.fieldErrors = fieldErrors;`);
	lines.push(`\t}`);
	lines.push(`}`);
	lines.push('');

	// Types
	lines.push(`// ── Types ──────────────────────────────────────`);
	lines.push('');
	lines.push(`export type AuthConfig =`);
	lines.push(`\t| { type: 'cookie' }`);
	lines.push(`\t| { type: 'apiKey'; key: string }`);
	lines.push(`\t| { type: 'bearer'; token: string };`);
	lines.push('');
	lines.push(`export interface MomentumClientConfig {`);
	lines.push(`\tbaseUrl: string;`);
	lines.push(`\tauth?: AuthConfig;`);
	lines.push(`\theaders?: Record<string, string>;`);
	lines.push(`\tfetch?: typeof globalThis.fetch;`);
	lines.push(`}`);
	lines.push('');
	lines.push(`export interface FindOptions {`);
	lines.push(`\twhere?: Record<string, unknown>;`);
	lines.push(`\tsort?: string;`);
	lines.push(`\tlimit?: number;`);
	lines.push(`\tpage?: number;`);
	lines.push(`\tdepth?: number;`);
	lines.push(`\twithDeleted?: boolean;`);
	lines.push(`\tonlyDeleted?: boolean;`);
	lines.push(`}`);
	lines.push('');
	lines.push(`export interface FindByIdOptions {`);
	lines.push(`\tdepth?: number;`);
	lines.push(`\twithDeleted?: boolean;`);
	lines.push(`}`);
	lines.push('');
	lines.push(`export interface FindResult<T> {`);
	lines.push(`\tdocs: T[];`);
	lines.push(`\ttotalDocs: number;`);
	lines.push(`\ttotalPages: number;`);
	lines.push(`\tpage: number;`);
	lines.push(`\tlimit: number;`);
	lines.push(`\thasNextPage: boolean;`);
	lines.push(`\thasPrevPage: boolean;`);
	lines.push(`\tnextPage?: number;`);
	lines.push(`\tprevPage?: number;`);
	lines.push(`}`);
	lines.push('');
	lines.push(`export interface DeleteResult {`);
	lines.push(`\tid: string;`);
	lines.push(`\tdeleted: boolean;`);
	lines.push(`}`);
	lines.push('');

	// Internal config type
	lines.push(`// ── Internals ──────────────────────────────────`);
	lines.push('');
	lines.push(`interface InternalConfig {`);
	lines.push(`\tbaseUrl: string;`);
	lines.push(`\theaders: Record<string, string>;`);
	lines.push(`\tfetchFn: typeof globalThis.fetch;`);
	lines.push(`}`);
	lines.push('');

	// Resolve config helper
	lines.push(`function resolveConfig(config: MomentumClientConfig): InternalConfig {`);
	lines.push(
		`\tconst headers: Record<string, string> = { 'Content-Type': 'application/json', ...config.headers };`,
	);
	lines.push(`\tif (config.auth?.type === 'apiKey') {`);
	lines.push(`\t\theaders['X-API-Key'] = config.auth.key;`);
	lines.push(`\t} else if (config.auth?.type === 'bearer') {`);
	lines.push(`\t\theaders['Authorization'] = \`Bearer \${config.auth.token}\`;`);
	lines.push(`\t}`);
	lines.push(`\treturn {`);
	lines.push(`\t\tbaseUrl: config.baseUrl.replace(/\\/+$/, ''),`);
	lines.push(`\t\theaders,`);
	lines.push(`\t\tfetchFn: config.fetch ?? globalThis.fetch.bind(globalThis),`);
	lines.push(`\t};`);
	lines.push(`}`);
	lines.push('');

	// Fetch wrapper
	lines.push(
		`async function momentumFetch<T>(url: string, init: RequestInit, config: InternalConfig): Promise<T> {`,
	);
	lines.push(`\tlet response: Response;`);
	lines.push(`\ttry {`);
	lines.push(`\t\tresponse = await config.fetchFn(url, {`);
	lines.push(`\t\t\t...init,`);
	lines.push(`\t\t\theaders: { ...config.headers, ...init.headers as Record<string, string> },`);
	lines.push(`\t\t\tcredentials: 'include',`);
	lines.push(`\t\t});`);
	lines.push(`\t} catch {`);
	lines.push(`\t\tthrow new MomentumClientError('Network error', 0);`);
	lines.push(`\t}`);
	lines.push(`\tif (!response.ok) {`);
	lines.push(
		`\t\tlet body: { error?: string; errors?: Array<{ field: string; message: string }> } = {};`,
	);
	lines.push(`\t\ttry { body = await response.json(); } catch { /* non-JSON error */ }`);
	lines.push(`\t\tthrow new MomentumClientError(`);
	lines.push(`\t\t\tbody.error ?? \`HTTP \${response.status}\`,`);
	lines.push(`\t\t\tresponse.status,`);
	lines.push(`\t\t\tbody.errors ?? [],`);
	lines.push(`\t\t);`);
	lines.push(`\t}`);
	lines.push(`\treturn response.json() as Promise<T>;`);
	lines.push(`}`);
	lines.push('');

	// Query string builder
	lines.push(
		`function buildQueryString(options?: FindOptions & Record<string, unknown>): string {`,
	);
	lines.push(`\tif (!options) return '';`);
	lines.push(`\tconst params: string[] = [];`);
	lines.push(`\tif (options.limit !== undefined) params.push(\`limit=\${options.limit}\`);`);
	lines.push(`\tif (options.page !== undefined) params.push(\`page=\${options.page}\`);`);
	lines.push(
		`\tif (options.sort !== undefined) params.push(\`sort=\${encodeURIComponent(options.sort)}\`);`,
	);
	lines.push(`\tif (options.depth !== undefined) params.push(\`depth=\${options.depth}\`);`);
	lines.push(`\tif (options.withDeleted) params.push('withDeleted=true');`);
	lines.push(`\tif (options.onlyDeleted) params.push('onlyDeleted=true');`);
	lines.push(
		`\tif (options.where !== undefined) params.push(\`where=\${encodeURIComponent(JSON.stringify(options.where))}\`);`,
	);
	lines.push(`\treturn params.length > 0 ? \`?\${params.join('&')}\` : '';`);
	lines.push(`}`);
	lines.push('');

	// CollectionClient class
	lines.push(`// ── Collection Client ──────────────────────────`);
	lines.push('');
	lines.push(`class CollectionClient<T, W = Record<string, unknown>> {`);
	lines.push(`\tprivate readonly slug: string;`);
	lines.push(
		`\tconstructor(private readonly config: InternalConfig, private readonly baseUrl: string, slug: string) {`,
	);
	lines.push(`\t\tthis.slug = encodeURIComponent(slug);`);
	lines.push(`\t}`);
	lines.push('');
	lines.push(`\tasync find(options?: FindOptions & { where?: W }): Promise<FindResult<T>> {`);
	lines.push(`\t\tconst qs = buildQueryString(options as FindOptions & Record<string, unknown>);`);
	lines.push(
		`\t\tconst res = await momentumFetch<FindResult<T>>(\`\${this.baseUrl}/\${this.slug}\${qs}\`, { method: 'GET' }, this.config);`,
	);
	lines.push(`\t\treturn res;`);
	lines.push(`\t}`);
	lines.push('');
	lines.push(`\tasync findById(id: string, options?: FindByIdOptions): Promise<T> {`);
	lines.push(`\t\tconst params: string[] = [];`);
	lines.push(`\t\tif (options?.depth !== undefined) params.push(\`depth=\${options.depth}\`);`);
	lines.push(`\t\tif (options?.withDeleted) params.push('withDeleted=true');`);
	lines.push(`\t\tconst qs = params.length > 0 ? \`?\${params.join('&')}\` : '';`);
	lines.push(
		`\t\tconst res = await momentumFetch<{ doc: T }>(\`\${this.baseUrl}/\${this.slug}/\${encodeURIComponent(id)}\${qs}\`, { method: 'GET' }, this.config);`,
	);
	lines.push(`\t\treturn res.doc;`);
	lines.push(`\t}`);
	lines.push('');
	lines.push(`\tasync create(data: Partial<T>): Promise<T> {`);
	lines.push(
		`\t\tconst res = await momentumFetch<{ doc: T }>(\`\${this.baseUrl}/\${this.slug}\`, { method: 'POST', body: JSON.stringify(data) }, this.config);`,
	);
	lines.push(`\t\treturn res.doc;`);
	lines.push(`\t}`);
	lines.push('');
	lines.push(`\tasync update(id: string, data: Partial<T>): Promise<T> {`);
	lines.push(
		`\t\tconst res = await momentumFetch<{ doc: T }>(\`\${this.baseUrl}/\${this.slug}/\${encodeURIComponent(id)}\`, { method: 'PATCH', body: JSON.stringify(data) }, this.config);`,
	);
	lines.push(`\t\treturn res.doc;`);
	lines.push(`\t}`);
	lines.push('');
	lines.push(`\tasync delete(id: string): Promise<DeleteResult> {`);
	lines.push(
		`\t\treturn momentumFetch<DeleteResult>(\`\${this.baseUrl}/\${this.slug}/\${encodeURIComponent(id)}\`, { method: 'DELETE' }, this.config);`,
	);
	lines.push(`\t}`);
	lines.push('');
	lines.push(`\tasync forceDelete(id: string): Promise<DeleteResult> {`);
	lines.push(
		`\t\treturn momentumFetch<DeleteResult>(\`\${this.baseUrl}/\${this.slug}/\${encodeURIComponent(id)}?force=true\`, { method: 'DELETE' }, this.config);`,
	);
	lines.push(`\t}`);
	lines.push('');
	lines.push(`\tasync restore(id: string): Promise<T> {`);
	lines.push(
		`\t\tconst res = await momentumFetch<{ doc: T }>(\`\${this.baseUrl}/\${this.slug}/\${encodeURIComponent(id)}/restore\`, { method: 'POST', body: '{}' }, this.config);`,
	);
	lines.push(`\t\treturn res.doc;`);
	lines.push(`\t}`);
	lines.push('');
	lines.push(`\tasync count(where?: W): Promise<number> {`);
	lines.push(`\t\tconst options: FindOptions = { limit: 0 };`);
	lines.push(`\t\tif (where) (options as Record<string, unknown>).where = where;`);
	lines.push(`\t\tconst res = await this.find(options as FindOptions & { where?: W });`);
	lines.push(`\t\treturn res.totalDocs;`);
	lines.push(`\t}`);
	lines.push('');
	lines.push(`\tasync batchCreate(items: Partial<T>[]): Promise<T[]> {`);
	lines.push(
		`\t\tconst res = await momentumFetch<{ docs: T[] }>(\`\${this.baseUrl}/\${this.slug}/batch\`, { method: 'POST', body: JSON.stringify({ operation: 'create', items }) }, this.config);`,
	);
	lines.push(`\t\treturn res.docs;`);
	lines.push(`\t}`);
	lines.push('');
	lines.push(`\tasync batchUpdate(items: { id: string; data: Partial<T> }[]): Promise<T[]> {`);
	lines.push(
		`\t\tconst res = await momentumFetch<{ docs: T[] }>(\`\${this.baseUrl}/\${this.slug}/batch\`, { method: 'POST', body: JSON.stringify({ operation: 'update', items }) }, this.config);`,
	);
	lines.push(`\t\treturn res.docs;`);
	lines.push(`\t}`);
	lines.push('');
	lines.push(`\tasync batchDelete(ids: string[]): Promise<DeleteResult[]> {`);
	lines.push(
		`\t\tconst res = await momentumFetch<{ results: DeleteResult[] }>(\`\${this.baseUrl}/\${this.slug}/batch\`, { method: 'POST', body: JSON.stringify({ operation: 'delete', ids }) }, this.config);`,
	);
	lines.push(`\t\treturn res.results;`);
	lines.push(`\t}`);
	lines.push(`}`);
	lines.push('');

	// GlobalClient class
	lines.push(`// ── Global Client ─────────────────────────────`);
	lines.push('');
	lines.push(`class GlobalClient<T> {`);
	lines.push(`\tprivate readonly slug: string;`);
	lines.push(
		`\tconstructor(private readonly config: InternalConfig, private readonly baseUrl: string, slug: string) {`,
	);
	lines.push(`\t\tthis.slug = encodeURIComponent(slug);`);
	lines.push(`\t}`);
	lines.push('');
	lines.push(`\tasync findOne(options?: { depth?: number }): Promise<T> {`);
	lines.push(`\t\tconst qs = options?.depth !== undefined ? \`?depth=\${options.depth}\` : '';`);
	lines.push(
		`\t\tconst res = await momentumFetch<{ doc: T }>(\`\${this.baseUrl}/globals/\${this.slug}\${qs}\`, { method: 'GET' }, this.config);`,
	);
	lines.push(`\t\treturn res.doc;`);
	lines.push(`\t}`);
	lines.push('');
	lines.push(`\tasync update(data: Partial<T>): Promise<T> {`);
	lines.push(
		`\t\tconst res = await momentumFetch<{ doc: T }>(\`\${this.baseUrl}/globals/\${this.slug}\`, { method: 'PATCH', body: JSON.stringify(data) }, this.config);`,
	);
	lines.push(`\t\treturn res.doc;`);
	lines.push(`\t}`);
	lines.push(`}`);
	lines.push('');

	// Factory function
	lines.push(`// ── Factory ───────────────────────────────────`);
	lines.push('');
	lines.push(`export function createMomentumClient(config: MomentumClientConfig) {`);
	lines.push(`\tconst ic = resolveConfig(config);`);
	lines.push(`\treturn {`);

	// Collections object
	lines.push(`\t\tcollections: {`);
	for (const col of allCollections) {
		const name = slugToPascalCase(col.slug);
		const key = needsQuoting(col.slug) ? safeQuote(col.slug) : col.slug;
		lines.push(
			`\t\t\t${key}: new CollectionClient<${name}, ${name}WhereClause>(ic, ic.baseUrl, ${safeQuote(col.slug)}),`,
		);
	}
	lines.push(`\t\t},`);

	// Globals object
	lines.push(`\t\tglobals: {`);
	for (const global of globals) {
		const name = slugToPascalCase(global.slug) + 'Global';
		const key = needsQuoting(global.slug) ? safeQuote(global.slug) : global.slug;
		lines.push(
			`\t\t\t${key}: new GlobalClient<${name}>(ic, ic.baseUrl, ${safeQuote(global.slug)}),`,
		);
	}
	lines.push(`\t\t},`);

	// Generic fallback methods
	lines.push(
		`\t\tcollection: <T = Record<string, unknown>>(slug: string) => new CollectionClient<T>(ic, ic.baseUrl, slug),`,
	);
	lines.push(
		`\t\tglobal: <T = Record<string, unknown>>(slug: string) => new GlobalClient<T>(ic, ic.baseUrl, slug),`,
	);
	lines.push(`\t};`);
	lines.push(`}`);
	lines.push('');

	return lines.join('\n');
}
