/**
 * Generate the browser-safe admin config TypeScript file.
 * Collections and globals are inlined with server-only properties stripped.
 * Only plugin admin routes are still imported (they have loadComponent functions).
 */

import {
	serializeValue,
	serializeCollection,
	serializeGlobal,
	serializeComponentLoaders,
} from './serialization';
import type { MomentumConfig } from './generator-types';
import { resolveAllCollections } from './generator-types';

export function generateAdminConfig(
	config: MomentumConfig,
	typesRelPath: string,
	configPath?: string,
	outputPath?: string,
): string {
	const lines: string[] = [];
	const allCollections = resolveAllCollections(config);
	const globals = config.globals ?? [];
	const plugins = config.plugins ?? [];

	// Plugins that have admin routes with browser imports (validate exportName is a safe identifier)
	const SAFE_IDENTIFIER = /^[a-zA-Z_$][a-zA-Z0-9_$]*$/;
	const pluginsWithAdminRoutes = plugins.filter((p) => {
		if (!p.browserImports?.adminRoutes || !p.adminRoutes || p.adminRoutes.length === 0)
			return false;
		const exportName = p.browserImports.adminRoutes.exportName;
		if (!SAFE_IDENTIFIER.test(exportName)) {
			console.warn(
				`[generateAdminConfig] Skipping plugin "${p.name}": exportName "${exportName}" is not a valid identifier`,
			);
			return false;
		}
		return true;
	});

	// Header
	lines.push('/**');
	lines.push(' * AUTO-GENERATED by @momentumcms/core');
	lines.push(' * DO NOT EDIT - regenerate with: nx run <app>:generate');
	lines.push(' */');
	lines.push('');

	// Imports
	lines.push("import type { MomentumAdminConfig } from '@momentumcms/core';");

	// Import slug types from types file
	const typeImports: string[] = ['CollectionSlug'];
	if (globals.length > 0) {
		typeImports.push('GlobalSlug');
	}
	lines.push(`import type { ${typeImports.join(', ')} } from ${JSON.stringify(typesRelPath)};`);

	// Import plugin admin routes
	for (const plugin of pluginsWithAdminRoutes) {
		const imp = plugin.browserImports?.adminRoutes;
		if (!imp) continue;
		lines.push(`import { ${imp.exportName} } from ${JSON.stringify(imp.path)};`);
	}

	lines.push('');

	// Export typed config
	const genericParams = globals.length > 0 ? '<CollectionSlug, GlobalSlug>' : '<CollectionSlug>';
	lines.push(`export const adminConfig: MomentumAdminConfig${genericParams} = {`);

	// Collections (inlined)
	if (allCollections.length > 0) {
		const collectionItems = allCollections
			.map((c) => `\t\t${serializeCollection(c, '\t\t', configPath, outputPath)}`)
			.join(',\n');
		lines.push(`\tcollections: [\n${collectionItems},\n\t],`);
	} else {
		lines.push('\tcollections: [],');
	}

	// Globals (inlined)
	if (globals.length > 0) {
		const globalItems = globals.map((g) => `\t\t${serializeGlobal(g, '\t\t')}`).join(',\n');
		lines.push(`\tglobals: [\n${globalItems},\n\t],`);
	}

	// Admin settings
	if (config.admin) {
		const adminParts: string[] = [];
		if (config.admin.basePath) {
			adminParts.push(`\t\tbasePath: ${JSON.stringify(config.admin.basePath)}`);
		}
		if (config.admin.branding) {
			adminParts.push(`\t\tbranding: ${serializeValue(config.admin.branding, '\t\t')}`);
		}
		if (config.admin.toasts !== undefined) {
			adminParts.push(`\t\ttoasts: ${String(config.admin.toasts)}`);
		}

		// Serialize component loaders with path rewriting
		if (config.admin.components && configPath && outputPath) {
			const componentsStr = serializeComponentLoaders(
				config.admin.components,
				configPath,
				outputPath,
				'\t\t',
			);
			if (componentsStr) {
				adminParts.push(`\t\tcomponents: ${componentsStr}`);
			}
		}

		if (adminParts.length > 0) {
			lines.push(`\tadmin: {\n${adminParts.join(',\n')},\n\t},`);
		}
	}

	// Plugin descriptors (only those with admin routes)
	if (pluginsWithAdminRoutes.length > 0) {
		const pluginItems = pluginsWithAdminRoutes
			.flatMap((p) => {
				const imp = p.browserImports?.adminRoutes;
				if (!imp) return [];
				return [`\t\t{ name: ${JSON.stringify(p.name)}, adminRoutes: ${imp.exportName} }`];
			})
			.join(',\n');
		lines.push(`\tplugins: [\n${pluginItems},\n\t],`);
	}

	lines.push('};');
	lines.push('');

	return lines.join('\n');
}
