/**
 * Generate TypeScript type declarations from collection and global definitions.
 */

import {
	slugToPascalCase,
	fieldTypeToTS,
	generateFieldsInterface,
	generateBlockTypes,
	generateWhereClauseInterface,
	safeQuote,
	needsQuoting,
} from './field-to-typescript';
import { flattenDataFields } from '../lib/fields/field.types';
import type { Field } from '../lib/fields/field.types';
import type { MomentumConfig } from './generator-types';
import { resolveAllCollections, hasVersionsWithDrafts } from './generator-types';

/**
 * Generate TypeScript types from collection and global definitions.
 */
export function generateTypes(config: MomentumConfig): string {
	const allCollections = resolveAllCollections(config);
	const globals = config.globals ?? [];
	const lines: string[] = [];

	// Header
	lines.push('/**');
	lines.push(' * AUTO-GENERATED by @momentumcms/core');
	lines.push(' * DO NOT EDIT - regenerate with: nx run <app>:generate');
	lines.push(' */');
	lines.push('');

	// Collect block type declarations that need to appear before their parent interface
	const blockDeclarations: string[] = [];

	// Generate interface for each collection
	for (const collection of allCollections) {
		const interfaceName = slugToPascalCase(collection.slug);
		// eslint-disable-next-line @typescript-eslint/consistent-type-assertions -- boundary: local FieldDefinition[] → library Field[]
		const dataFields = flattenDataFields(collection.fields as Field[]);
		const hasVersionsDrafts = hasVersionsWithDrafts(collection);
		const hasSoftDelete = !!collection.softDelete;
		const hasTimestamps = collection.timestamps !== false;

		// Pre-generate block types for any blocks fields
		for (const field of dataFields) {
			if (field.type === 'blocks') {
				const blockResult = generateBlockTypes(collection.slug, field.name, field);
				blockDeclarations.push(blockResult.declarations);
			}
		}

		// Output any pending block declarations before this interface
		if (blockDeclarations.length > 0) {
			lines.push(blockDeclarations.join('\n'));
			blockDeclarations.length = 0;
		}

		lines.push(`export interface ${interfaceName} {`);
		lines.push(`  id: string;`);

		// Generate fields
		for (const field of dataFields) {
			const optional = field.required ? '' : '?';
			const propName = needsQuoting(field.name) ? safeQuote(field.name) : field.name;

			if (field.type === 'blocks') {
				// Use the generated union type name
				const blockResult = generateBlockTypes(collection.slug, field.name, field);
				lines.push(`  ${propName}${optional}: ${blockResult.unionTypeName}[];`);
			} else {
				const tsType = fieldTypeToTS(field);
				lines.push(`  ${propName}${optional}: ${tsType};`);
			}
		}

		// Version status field
		if (hasVersionsDrafts) {
			lines.push(`  _status?: 'draft' | 'published';`);
		}

		// Soft delete field
		if (hasSoftDelete) {
			const fieldName =
				typeof collection.softDelete === 'object' && collection.softDelete.field
					? collection.softDelete.field
					: 'deletedAt';
			lines.push(`  ${fieldName}?: string | null;`);
		}

		// Timestamps
		if (hasTimestamps) {
			lines.push(`  createdAt: string;`);
			lines.push(`  updatedAt: string;`);
		}

		lines.push(`}`);
		lines.push('');
	}

	// Generate global types
	if (globals.length > 0) {
		lines.push('// ── Global Types ───────────────────────────────');
		lines.push('');

		for (const global of globals) {
			const interfaceName = slugToPascalCase(global.slug) + 'Global';
			// eslint-disable-next-line @typescript-eslint/consistent-type-assertions -- boundary: local FieldDefinition[] → library Field[]
			const fieldsCode = generateFieldsInterface(global.fields as Field[]);

			lines.push(`export interface ${interfaceName} {`);
			if (fieldsCode) {
				lines.push(fieldsCode);
			}
			lines.push(`  updatedAt: string;`);
			lines.push(`}`);
			lines.push('');
		}
	}

	// Generate where clause interfaces
	lines.push('// ── Where Clauses ──────────────────────────────');
	lines.push('');

	for (const collection of allCollections) {
		const hasTimestamps = collection.timestamps !== false;
		lines.push(
			// eslint-disable-next-line @typescript-eslint/consistent-type-assertions -- boundary: local FieldDefinition[] → library Field[]
			generateWhereClauseInterface(collection.slug, collection.fields as Field[], hasTimestamps),
		);
		lines.push('');
	}

	// Collection slug union
	const slugs = allCollections.map((c) => safeQuote(c.slug)).join(' | ');
	lines.push(`export type CollectionSlug = ${slugs || 'never'};`);
	lines.push('');

	// Global slug union
	if (globals.length > 0) {
		const globalSlugs = globals.map((g) => safeQuote(g.slug)).join(' | ');
		lines.push(`export type GlobalSlug = ${globalSlugs};`);
		lines.push('');
	}

	// MomentumCollections mapping
	lines.push(`export interface MomentumCollections {`);
	for (const collection of allCollections) {
		const interfaceName = slugToPascalCase(collection.slug);
		lines.push(`  ${safeQuote(collection.slug)}: ${interfaceName};`);
	}
	lines.push(`}`);
	lines.push('');

	// MomentumGlobals mapping
	if (globals.length > 0) {
		lines.push(`export interface MomentumGlobals {`);
		for (const global of globals) {
			const interfaceName = slugToPascalCase(global.slug) + 'Global';
			lines.push(`  ${safeQuote(global.slug)}: ${interfaceName};`);
		}
		lines.push(`}`);
		lines.push('');
	}

	// TypedMomentumCollections
	lines.push(`export type TypedMomentumCollections = {`);
	for (const collection of allCollections) {
		const interfaceName = slugToPascalCase(collection.slug);
		lines.push(
			`  ${safeQuote(collection.slug)}: { doc: ${interfaceName}; where: ${interfaceName}WhereClause };`,
		);
	}
	lines.push(`};`);
	lines.push('');

	// Helper types
	lines.push(`export type DocumentType<S extends CollectionSlug> = MomentumCollections[S];`);
	lines.push('');
	lines.push(
		`export type WhereClauseType<S extends CollectionSlug> = TypedMomentumCollections[S]['where'];`,
	);
	lines.push('');

	return lines.join('\n');
}
