/**
 * Migration Operation Types
 *
 * Represents all possible schema change operations.
 * Generated by the diff engine, consumed by migration file generator and runner.
 */

// ============================================
// Table Operations
// ============================================

export interface CreateTableOperation {
	readonly type: 'createTable';
	readonly table: string;
	readonly columns: ReadonlyArray<{
		name: string;
		type: string;
		nullable: boolean;
		defaultValue?: string;
		primaryKey?: boolean;
	}>;
}

export interface DropTableOperation {
	readonly type: 'dropTable';
	readonly table: string;
}

export interface RenameTableOperation {
	readonly type: 'renameTable';
	readonly from: string;
	readonly to: string;
}

// ============================================
// Column Operations
// ============================================

export interface AddColumnOperation {
	readonly type: 'addColumn';
	readonly table: string;
	readonly column: string;
	readonly columnType: string;
	readonly nullable: boolean;
	readonly defaultValue?: string;
}

export interface DropColumnOperation {
	readonly type: 'dropColumn';
	readonly table: string;
	readonly column: string;
	/** Previous type, for generating down() */
	readonly previousType?: string;
	readonly previousNullable?: boolean;
}

export interface AlterColumnTypeOperation {
	readonly type: 'alterColumnType';
	readonly table: string;
	readonly column: string;
	readonly fromType: string;
	readonly toType: string;
	/** Optional USING clause for PostgreSQL type casts */
	readonly castExpression?: string;
}

export interface AlterColumnNullableOperation {
	readonly type: 'alterColumnNullable';
	readonly table: string;
	readonly column: string;
	readonly nullable: boolean;
}

export interface AlterColumnDefaultOperation {
	readonly type: 'alterColumnDefault';
	readonly table: string;
	readonly column: string;
	readonly defaultValue: string | null;
	readonly previousDefault: string | null;
}

export interface RenameColumnOperation {
	readonly type: 'renameColumn';
	readonly table: string;
	readonly from: string;
	readonly to: string;
}

// ============================================
// Foreign Key Operations
// ============================================

export interface AddForeignKeyOperation {
	readonly type: 'addForeignKey';
	readonly table: string;
	readonly constraintName: string;
	readonly column: string;
	readonly referencedTable: string;
	readonly referencedColumn: string;
	readonly onDelete: string;
}

export interface DropForeignKeyOperation {
	readonly type: 'dropForeignKey';
	readonly table: string;
	readonly constraintName: string;
}

// ============================================
// Index Operations
// ============================================

export interface CreateIndexOperation {
	readonly type: 'createIndex';
	readonly table: string;
	readonly indexName: string;
	readonly columns: readonly string[];
	readonly unique: boolean;
}

export interface DropIndexOperation {
	readonly type: 'dropIndex';
	readonly table: string;
	readonly indexName: string;
}

// ============================================
// Raw SQL Operation
// ============================================

export interface RawSqlOperation {
	readonly type: 'rawSql';
	readonly upSql: string;
	readonly downSql: string;
	readonly description: string;
}

// ============================================
// Union Type
// ============================================

/**
 * All possible migration operations.
 */
export type MigrationOperation =
	| CreateTableOperation
	| DropTableOperation
	| RenameTableOperation
	| AddColumnOperation
	| DropColumnOperation
	| AlterColumnTypeOperation
	| AlterColumnNullableOperation
	| AlterColumnDefaultOperation
	| RenameColumnOperation
	| AddForeignKeyOperation
	| DropForeignKeyOperation
	| CreateIndexOperation
	| DropIndexOperation
	| RawSqlOperation;
